# Generated by Django 4.0.3 on 2022-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_first_name_user_last_name_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Due', 'Due'), ('Paid', 'Paid'), ('Pending', 'Pending')], max_length=255, null=True),
        ),
    ]
